vich_uploader:
    db_driver: orm

    mappings:
        playlist:
            uri_prefix: /images/playlist
            upload_destination: '%kernel.project_dir%/public/images/playlist'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
