<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Post;
use App\Entity\UserInfo;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\HttpFoundation\Request;


class PostController extends AbstractController
{
    /**
     * @Route("/post", name="post")
     */
    public function index(Request $request): Response
    {



        $post = new Post();

        $form = $this->createFormBuilder($post)
            ->add(
                'text',
                TextareaType::class,
                [
                    'attr' => [
                        'class' => 'textarea bg-transparent has-text-white'

                    ]
                ]
            )
            ->add(
                'postImage',
                FileType::class,
                [
                    'attr' => [
                        'class' => 'file-input',

                    ],
                    'required' => false
                ]
            )
            ->getForm();


        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $repo1 = $this->getDoctrine()->getRepository(UserInfo::class);
            $user = $repo1->find(4);
            $post->setUser($user)
                ->setCreatedAt(new \DateTime());

            dump($post);



            /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
            $file = $post->getPostImage();


            if ($file) {
                $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();

               dump( $this->getParameter('post_images_directory'));

                $file->move(
                    $this->getParameter('post_images_directory'),
                    $fileName
                );

                $post->setPostImage($fileName);
            }




            $em = $this->getDoctrine()->getManager();
            $em->persist($post);
            $em->flush();
        }

        $repo = $this->getDoctrine()->getRepository(Post::class);
        $posts = $repo->findAll();


        //story Time


        



        return $this->render('post/index.html.twig', [
            'controller_name' => 'PostController',
            'posts' => $posts,
            'formPost' => $form->createView(),
            //story variables
            
        ]);
    }


    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
